{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index [logstash]",
        "resource.type" : "index_or_alias",
        "resource.id" : "logstash",
        "index_uuid" : "_na_",
        "index" : "logstash"
      }
    ],
    "type" : "index_not_found_exception",
    "reason" : "no such index [logstash]",
    "resource.type" : "index_or_alias",
    "resource.id" : "logstash",
    "index_uuid" : "_na_",
    "index" : "logstash"
  },
  "status" : 404
}
